cabal-version:       3.4
name:                wavefront
version:             0.7.1.5
synopsis:            Wavefront OBJ loader
description:         A Wavefront OBJ loader. Currently supports polygonal information. More could
                     be added if needed (like curves and surface) if people contribute. Feel free
                     to help!
homepage:            https://github.com/phaazon/wavefront
bug-reports:         https://github.com/phaazon/wavefront/issues
license:             BSD-3-Clause
license-file:        LICENSE
author:              Dimitri Sabadie <dimitri.sabadie@gmail.com>
maintainer:          Dimitri Sabadie <dimitri.sabadie@gmail.com>
copyright:           Dimitri Sabadie

category:            Codec
build-type:          Simple
extra-doc-files:
    README.md
    CHANGELOG.md
data-dir:            data

tested-with:
    GHC == 9.12.2
  , GHC == 9.10.1

source-repository head
  type:     git
  location: git://github.com/phaazon/wavefront.git

library
  ghc-options:         -W -Wall

  exposed-modules:     Codec.Wavefront
                     , Codec.Wavefront.Element
                     , Codec.Wavefront.Face
                     , Codec.Wavefront.IO
                     , Codec.Wavefront.Location
                     , Codec.Wavefront.Line
                     , Codec.Wavefront.Normal
                     , Codec.Wavefront.Object
                     , Codec.Wavefront.Point
                     , Codec.Wavefront.TexCoord


                     , Codec.Wavefront.Material
                     , Codec.Wavefront.Material.Type
                     , Codec.Wavefront.Material.Token
                     , Codec.Wavefront.Material.Lexer


                     , Codec.Wavefront.Token
                     , Codec.Wavefront.Lexer
                     , Codec.Wavefront.SizedDList

  -- other-modules:       Codec.Wavefront.Token
  --                    , Codec.Wavefront.Lexer
  --                    , Codec.Wavefront.SizedDList


  default-extensions:  OverloadedStrings

  build-depends:       base         >= 4.8  && < 4.22
                     , attoparsec   >= 0.13 && < 0.15
                     , dlist        >= 0.7  && < 1.1
                     , filepath     >= 1.4  && < 1.6
                     , mtl          >= 2.2  && < 2.4
                     , text         >= 1.2  && < 2.2
                     , transformers >= 0.4  && < 0.7
                     , vector       >= 0.11 && < 0.14
                     , containers   >= 0.7  && < 0.8

  hs-source-dirs:      src

  default-language:    Haskell2010

--------------------------------------------------------------------------------

test-suite hspec
  build-tool-depends: hspec-discover:hspec-discover
  type:             exitcode-stdio-1.0
  main-is:          Main.hs
  hs-source-dirs: test
  other-modules:
      Spec
      ParseSpec
      Paths_wavefront
  autogen-modules:
      Paths_wavefront
  build-depends:
                       base
                     , wavefront
                     , hspec                           >= 2.9     && < 3
                     , text
                     , attoparsec

  default-language:    Haskell2010
